### ISSUE TITLE
Login and Register issues.

### ISSUE THREAD

**Issue by CozmoDev** [orcfoss/Rboxlo#107]
Hello. I am having issues with registering and logging in. Registering on the front page will just bring you to a page with the text "Forbidden". If I go on the normal registering page and try to register , it does work , but it will be loading forever until you go back to any other page. Then I can login , but its loading forever again and going on another page wont log me in.

**Comment by lightbulblighter** [comment]
Seems like a CSRF issue... this is a tough one to figure out without knowing what browser you have, as CSRFs are kept in the browsers cookie jar. Try this:

- Run Rboxlo on stock settings (if you've changed anything severe inside the codebase, environment changes are fine and shouldn't cause an issue)
- Install a big name browser that you don't already have (Firefox, Chrome, Edge, Opera, etc.)
- Try submitting a form again and report your result

There's also the off chance that the server is not sending any CSRF tokens to the client, meaning that the CSRF middleware is messing up somewhere. This could be caused by an empty cookie and/or session key. Make sure to check that.

If the problem still persists, you can open up the register form or the login forms output HTML document and look for an "input" element with the name "_csrf" and look at its value attribute. It shouldn't be empty.

**Comment by CozmoDev** [comment]
Ok so , originally I was using chrome , but I tried it on Edge and Firefox and it still did the same thing as mentioned above. And also , I only modified the name for the website and some other necessary fields so that shouldn't be a problem. My cookie and session key fields are filled out so that is fine. Also I could not find the location of the HTML documents for the register and login forms.

**Comment by lightbulblighter** [comment]
> Ok so , originally I was using chrome , but I tried it on Edge and Firefox and it still did the same thing as mentioned above. And also , I only modified the name for the website and some other necessary fields so that shouldn't be a problem. My cookie and session key fields are filled out so that is fine. Also I could not find the location of the HTML documents for the register and login forms.

Everything seems to be working properly, then. There is no location for the documents; you must open the webpage source (right click and click "View source" or navigate to `view-source:https://rboxlo.loc` in your browser.) Please report back the results. 

As Rboxlo is currently only developed by me, and because I currently don't have access to the computer I'm using to work on Rboxlo, at this time I'm not able to reproduce nor test the issue. Sorry for the inconvenience. I'll be sure to check it out ASAP when I'm able to though.

**Comment by CozmoDev** [comment]
Hello , this is the html document , I have circled the _csrf part.
![image](https://user-images.githubusercontent.com/75683363/127314346-0abf57e9-33fc-4884-be88-0e6ec56c2362.png)

**Comment by lightbulblighter** [comment]
Seems like the CSRF token is never being set. Will address soon.

**Comment by William-J-Burns** [comment]
File: \Rboxlo\Server\websites\eclipse\views\home.handlebars

Line 46:
                          `<input type="hidden" name="_csrf" value="{{ object.csrf }}">`
Should be:
                           `<input type="hidden" name="_csrf" value="{{ session.csrf }}">`

**Comment by lightbulblighter** [comment]
Thanks @William-J-Burns . Will close this issue when I commit. Will credit you

**Comment by lightbulblighter** [comment]
For now, @CozmoDev use the solution William has suggested
